apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rm9u3g6jl-java-springboot
  janus-idp.io/tekton: rm9u3g6jl-java-springboot
  backstage.io/kubernetes-id: rm9u3g6jl-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rm9u3g6jl-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
